export enum ErrorCode {
  // Auth
  AUTH_EMAIL_TAKEN = 'AUTH_001',
  AUTH_INVALID_CREDENTIALS = 'AUTH_002',
  AUTH_UNAUTHORIZED = 'AUTH_003',

  VALIDATION_ERROR = 'VALIDATION_001',

  INTERNAL_ERROR = 'INTERNAL_001',
  NOT_FOUND = 'GENERAL_001',
}