-- AlterTable
ALTER TABLE "Monitor" ADD COLUMN     "consecutiveFailures" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "intervalMinutes" INTEGER NOT NULL DEFAULT 5,
ADD COLUMN     "status" TEXT NOT NULL DEFAULT 'ACTIVE';
